export var content_data = [
	{
		"id": 0,
		"title": "Techniczne SEO",
		"lead" : "Kilka słów o tym czym dlaczego SEO to nie tylko linki i content. ",
		"description": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mauris elit, pellentesque tristique efficitur eget, vehicula eget massa. Fusce et lorem ac nisi sollicitudin euismod. Phasellus fringilla ornare elit ac condimentum. Nunc egestas, odio ac mollis scelerisque, nisl mauris posuere justo, quis fermentum ligula tellus eu leo. Mauris sagittis justo vitae diam faucibus ornare. Maecenas libero sapien, euismod eget euismod vitae, eleifend in eros. Aenean rhoncus eget mauris et vehicula. Nunc accumsan, ex ut vulputate egestas, risus quam vestibulum lorem, ac pellentesque justo eros at nisi.</p><p>Aenean magna leo, lobortis nec urna vitae, accumsan blandit mauris. Sed in tortor eget nulla pulvinar blandit quis sed ligula. Suspendisse venenatis dapibus ultrices. Donec bibendum venenatis ante ut lobortis. Sed condimentum mauris sed diam sagittis ullamcorper. Pellentesque fringilla sem et sem varius, in vulputate nulla sagittis. Nulla tempor fringilla eros, non tincidunt felis porta sed. Pellentesque posuere vehicula lorem, et maximus leo luctus ut. Vivamus ultrices quam quis quam dignissim dictum. Ut malesuada felis non viverra vestibulum. Mauris ut vulputate massa, et accumsan odio.</p><p>Proin blandit est a orci dapibus, id efficitur velit sagittis. Sed id laoreet ante. Vivamus ac mi ligula. Maecenas bibendum nulla nec vulputate pharetra. Suspendisse dapibus arcu eu ornare viverra. Aenean interdum purus id dolor lacinia facilisis. Maecenas in urna nec elit porttitor vehicula eget ac massa.</p><p>Aliquam ultricies, lacus et tristique semper, metus arcu consequat sem, sed efficitur nibh orci bibendum libero. Quisque sed auctor mauris. Nunc nec tincidunt nisl, et vestibulum erat. Nulla iaculis, justo lacinia vestibulum pharetra, ex neque malesuada tortor, eu pharetra tellus eros vel risus. Sed sollicitudin tristique nibh ac laoreet. Suspendisse eleifend malesuada posuere. In nec pretium augue.</p>",
		"image": "http://eduweb.pl/Images/Training/miniaturka-do-opisu-kursu_27ded9b2-af48-4118-a02a-e35fe950a9be.png",
	},
	{
		"id": 1,
		"title": "JavaScript i SEO - bolączki SEOwca",
		"lead" : "Kilka słów o tym czym dlaczego SEO to nie tylko linki i content. ",
		"description": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mauris elit, pellentesque tristique efficitur eget, vehicula eget massa. Fusce et lorem ac nisi sollicitudin euismod. Phasellus fringilla ornare elit ac condimentum. Nunc egestas, odio ac mollis scelerisque, nisl mauris posuere justo, quis fermentum ligula tellus eu leo. Mauris sagittis justo vitae diam faucibus ornare. Maecenas libero sapien, euismod eget euismod vitae, eleifend in eros. Aenean rhoncus eget mauris et vehicula. Nunc accumsan, ex ut vulputate egestas, risus quam vestibulum lorem, ac pellentesque justo eros at nisi.</p><p>Aenean magna leo, lobortis nec urna vitae, accumsan blandit mauris. Sed in tortor eget nulla pulvinar blandit quis sed ligula. Suspendisse venenatis dapibus ultrices. Donec bibendum venenatis ante ut lobortis. Sed condimentum mauris sed diam sagittis ullamcorper. Pellentesque fringilla sem et sem varius, in vulputate nulla sagittis. Nulla tempor fringilla eros, non tincidunt felis porta sed. Pellentesque posuere vehicula lorem, et maximus leo luctus ut. Vivamus ultrices quam quis quam dignissim dictum. Ut malesuada felis non viverra vestibulum. Mauris ut vulputate massa, et accumsan odio.</p><p>Proin blandit est a orci dapibus, id efficitur velit sagittis. Sed id laoreet ante. Vivamus ac mi ligula. Maecenas bibendum nulla nec vulputate pharetra. Suspendisse dapibus arcu eu ornare viverra. Aenean interdum purus id dolor lacinia facilisis. Maecenas in urna nec elit porttitor vehicula eget ac massa.</p><p>Aliquam ultricies, lacus et tristique semper, metus arcu consequat sem, sed efficitur nibh orci bibendum libero. Quisque sed auctor mauris. Nunc nec tincidunt nisl, et vestibulum erat. Nulla iaculis, justo lacinia vestibulum pharetra, ex neque malesuada tortor, eu pharetra tellus eros vel risus. Sed sollicitudin tristique nibh ac laoreet. Suspendisse eleifend malesuada posuere. In nec pretium augue.</p>",
		"image": "http://eduweb.pl/Images/Training/miniaturka-do-opisu-kursu_9c8b5fd6-cda2-4b2f-881e-0039d189326e.png",

	},
	{
		"id": 2,
		"title": "React JS - framework",
		"lead" : "Kilka słów o tym czym dlaczego SEO to nie tylko linki i content. ",
		"description": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mauris elit, pellentesque tristique efficitur eget, vehicula eget massa. Fusce et lorem ac nisi sollicitudin euismod. Phasellus fringilla ornare elit ac condimentum. Nunc egestas, odio ac mollis scelerisque, nisl mauris posuere justo, quis fermentum ligula tellus eu leo. Mauris sagittis justo vitae diam faucibus ornare. Maecenas libero sapien, euismod eget euismod vitae, eleifend in eros. Aenean rhoncus eget mauris et vehicula. Nunc accumsan, ex ut vulputate egestas, risus quam vestibulum lorem, ac pellentesque justo eros at nisi.</p><p>Aenean magna leo, lobortis nec urna vitae, accumsan blandit mauris. Sed in tortor eget nulla pulvinar blandit quis sed ligula. Suspendisse venenatis dapibus ultrices. Donec bibendum venenatis ante ut lobortis. Sed condimentum mauris sed diam sagittis ullamcorper. Pellentesque fringilla sem et sem varius, in vulputate nulla sagittis. Nulla tempor fringilla eros, non tincidunt felis porta sed. Pellentesque posuere vehicula lorem, et maximus leo luctus ut. Vivamus ultrices quam quis quam dignissim dictum. Ut malesuada felis non viverra vestibulum. Mauris ut vulputate massa, et accumsan odio.</p><p>Proin blandit est a orci dapibus, id efficitur velit sagittis. Sed id laoreet ante. Vivamus ac mi ligula. Maecenas bibendum nulla nec vulputate pharetra. Suspendisse dapibus arcu eu ornare viverra. Aenean interdum purus id dolor lacinia facilisis. Maecenas in urna nec elit porttitor vehicula eget ac massa.</p><p>Aliquam ultricies, lacus et tristique semper, metus arcu consequat sem, sed efficitur nibh orci bibendum libero. Quisque sed auctor mauris. Nunc nec tincidunt nisl, et vestibulum erat. Nulla iaculis, justo lacinia vestibulum pharetra, ex neque malesuada tortor, eu pharetra tellus eros vel risus. Sed sollicitudin tristique nibh ac laoreet. Suspendisse eleifend malesuada posuere. In nec pretium augue.</p>",
		"image": "http://eduweb.pl/Images/Training/miniaturka-do-opisu-kursu_093c53c6-7395-4697-a141-4eae2db3d6a6.png",

	},
]